package exercises;

public class FibonacciTask {
	public static void main(String[] args) {
		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous
		 * two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * 
		 * By considering the terms in the Fibonacci sequence whose values do not exceed
		 * four million, find the sum of the even-valued terms.
		 */

		int first = 0;
		int second = 1;
		int fibbo = first + second;

		int sumOfEvenF = 0;

		for (int i = 0; i <= 2000; i++) {
			if (first <= 4000000) {
				if (first % 2 == 0) 
					sumOfEvenF += first;

					fibbo = first + second;
					first = second;
					second = fibbo;
				
			}
		}
		System.out.println(sumOfEvenF);
	}
}
